### ISSUE TITLE
Infinite Loop Launching Game

### ISSUE THREAD

**Issue by Jesse-Goertzen** [FoundationGames/Phonos#1]
I get stuck flipping between the main menu and the Mojang Loading screen. The Mojang Loading screen appears and reloads after briefly showing the main menu.

**Versions:**
Phonos: 0.1.0 Beta
Fabric Loader: 0.10.5+build.213
Fabric API: 0.24.3+build.414.-1.16
Patchouli: 1.16-36-FABRIC

`java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'net.minecraft.class_281 net.minecraft.class_281.method_1283(net.minecraft.class_281$class_282, java.lang.String, java.io.InputStream)'
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:94) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:116) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:103) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:308) ~[intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1043) [intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:656) [intermediary-minecraft-1.16.3-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.3-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-loader-0.10.5+build.213.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.10.5+build.213.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.10.5+build.213.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_281 net.minecraft.class_281.method_1283(net.minecraft.class_281$class_282, java.lang.String, java.io.InputStream)'
	at vazkii.patchouli.client.shader.ShaderHelper.loadProgram(ShaderHelper.java:50) ~[Patchouli-1.16-36-FABRIC.jar:?]
	at vazkii.patchouli.client.shader.ShaderHelper.method_14491(ShaderHelper.java:40) ~[Patchouli-1.16-36-FABRIC.jar:?]
	at net.minecraft.class_4013.method_29490(class_4013.java:15) ~[intermediary-minecraft-1.16.3-client.jar:?]
	... 194 more`

**Comment by Jesse-Goertzen** [comment]
Also occurs with Fabric API: 0.25.4+1.16 and Fabric Loader: 0.10.6+build.214

**Comment by FoundationGames** [comment]
This is an issue with Patchouli, not Phonos. You can see that patchouli is the only mod whose directories and classes are mentioned in the log. I would recommend you try again without phonos installed, and if the crash persists, please post it on Patchouli Fabric's issue tracker.

**Comment by Jesse-Goertzen** [comment]
Ah yes. Makes sense. Clearly I couldn't read last night because I thought I looked through the log. Will do.

**Comment by FoundationGames** [comment]
Could you please let me know if that resolved this issue, so I can close it?

**Comment by Jesse-Goertzen** [comment]
Hi, sorry. Yes it did fix the issue

**Comment by FoundationGames** [comment]
Thanks!
