### ISSUE TITLE
Radio Jukebox dissapears when attemped to pick up using carrier

### ISSUE THREAD

**Issue by JSJBDEV** [FoundationGames/Phonos#11]
```
java.lang.NullPointerException: null
	at io.github.foundationgames.phonos.block.RadioJukeboxBlock.method_9536(RadioJukeboxBlock.java:52) ~[phonos-0.1.1-beta.jar:?]
	at net.minecraft.class_4970$class_4971.method_26197(class_4970.java:870) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2818.method_12010(class_2818.java:276) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1937.method_30092(class_1937.java:231) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1937.method_8652(class_1937.java:217) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1937.method_8650(class_1937.java:291) ~[intermediary-1.16.5.jar:?]
	at me.steven.carrier.impl.CarriableGeneric.tryPickup(CarriableGeneric.java:50) ~[carrier-1.7.4.jar:?]
	at me.steven.carrier.HolderInteractCallback.interact(HolderInteractCallback.java:35) ~[carrier-1.7.4.jar:?]
	at me.steven.carrier.HolderInteractCallback.interact(HolderInteractCallback.java:74) ~[carrier-1.7.4.jar:?]
	at net.minecraft.class_4970$class_4971.handler$zna000$carrier_interactBlock(class_4970.java:2560) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:894) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3225.method_14262(class_3225.java:328) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_3244.method_12046(class_3244.java:1040) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2885.method_12547(class_2885.java:36) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_2600$$Lambda$9508/1627884596.run(Unknown Source) ~[?:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) [intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) [intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) [intermediary-1.16.5.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) [intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) [intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:674) [intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) [intermediary-1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$8880/1367075923.run(Unknown Source) [intermediary-1.16.5.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```
this appears in latest.log when the jukebox disappears, please also see https://github.com/GabrielOlvH/Carrier/issues/14

**Comment by FoundationGames** [comment]
Can this be tested with the 1.17 version of phonos? 1.16 is no longer supported and I'd like to know if the issue persists

**Comment by ThinkWithPbody** [comment]
Tested in 1.18.2 with phonos-0.3+1.18.2 and carrier-1.10.0. None of the phono blocks respond to the carrier hotkey, and this is the case too when holding the carrying glove for most other phono blocks except the radio jukebox. The jukebox isn't carried, it disappears along with the discs inside.

**Comment by FoundationGames** [comment]
Carrier is only for block entities, the only block entities in phonos are the jukebox and piano
I think this might be an issue with Carrier and for now it isn't supported until I investigate the issue myself
