### ISSUE TITLE
Crash when dying or unloading chunks containing a radio recorder

### ISSUE THREAD

**Issue by Justsnoopy30** [FoundationGames/Phonos#30]
Error: 
```
[17:36:34] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Ticking block entity
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:673) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:475) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:204) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1761) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1091) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [universe-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [universe-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [universe-loader-0.14.4.jar:?]
Caused by: java.lang.IllegalArgumentException: Cannot get property class_2746{name=powered, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
	at net.minecraft.class_2688.method_11654(class_2688.java:98) ~[client-intermediary.jar:?]
	at io.github.foundationgames.phonos.block.entity.RadioRecorderBlockEntity.tick(RadioRecorderBlockEntity.java:66) ~[phonos-0.3+1.18.2.jar:?]
	at net.minecraft.class_2818$class_5563.redirect$bfp000$checkProcessTEs(carpet/mixins/BoundTickingBlockEntity_tickMixin.java [carpet.mixins.json]:37) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659) ~[client-intermediary.jar:?]
	... 14 more
```
Crash report:
[crash-2022-05-08_19.25.11-client.txt](https://github.com/FoundationGames/Phonos/files/8647973/crash-2022-05-08_19.25.11-client.txt)

**Comment by Sebas-Re** [comment]
Same here, caused by a radio recorder, but the crash log is a bit different from yours: https://paste.corebot.dev/ozicagotoy.php

**Comment by AdalynBlack** [comment]
I am also having the same issue occur, It's the exact same issue for me as Sebas had

Edit: After looking at the stacktrace, I found the exact issue and fixed it myself. Replacing line 66 of the radio recorder block entity with `boolean powered = state.get(Properties.POWERED);` should fix the issue
