### ISSUE TITLE
Crash when used alongside Iron Jetpacks because of conflicting Artifice versions

### ISSUE THREAD

**Issue by WensenVos** [FoundationGames/Phonos#6]
I get the following crash error whenever I try to use **Phonos** alongside of the **Iron Jetpacks** mod:

```
Description: Initializing game

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "this.identifier" is null
	at com.swordglowsblue.artifice.impl.ArtificeResourcePackImpl.toClientResourcePackProfile(ArtificeResourcePackImpl.java:440)
	at com.swordglowsblue.artifice.impl.ArtificeAssetsResourcePackProvider.method_14453(ArtificeAssetsResourcePackProvider.java:20)
	at net.minecraft.class_3283.method_29212(class_3283.java:44)
	at net.minecraft.class_3283.method_14445(class_3283.java:37)
	at net.minecraft.class_310.redirect$cog000$enableNonOptional(class_310.java:18388)
	at net.minecraft.class_310.<init>(class_310.java:485)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
	
After some searching and tinkering, I narrowed down the cause due to differing versions of the **Artifice** library, Minecraft loads up properly when the **Artifice** jar from **Phonos** is extracted into the mods folder.

As a small work-around, this seems to cause **Iron Jetpacks** to work properly in spite of an older **Artifice** version being used.

**Iron Jetpacks** packages _artifice-0.14.4+1.16.3.jar_ inside of its jar, rather than _artifice-0.13.2+1.16.3.jar_ like **Phonos**, which causes the game to crash before reaching the main menu when both mods are installed within the same Minecraft instance.

**Comment by FoundationGames** [comment]
Hm... Might be a reason to possibly switch to ARRP, or even use FRAPI instead of models. I don't think constantly updating the JiJ-ed version of Artifice is a permanent solution, and I think it's good this has been reported to Artifice. Thanks for the contribution!

**Comment by ZaneDragonBorn** [comment]
https://pastebin.com/CV51iffb
I'm guessing this is my issue too. Is there a fix coming?

**Comment by ZaneDragonBorn** [comment]
Also, it seems even Uninstalling Iron JetPacks, it still will break. Maybe there are more mods with this issue? If you want the full Log just ask.

**Comment by FoundationGames** [comment]
Fixed, yote artifice
